package itinerary

import (
	"context"
	"fmt"
	"net/http"

	"inititaryplanner/models"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func A() {
	gin.New()
}

func (ic ItineraryController) CreateItinerary(c *gin.Context) {
	var newItinerary models.Itinerary

	// Bind JSON request body to newItinerary
	if err := c.ShouldBindJSON(&newItinerary); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf("Error decoding request body: %s", err.Error())})
		return
	}

	collection := ic.client.Database("mongo-golang").Collection("initieries")
	ctx := context.TODO()

	// Insert newItinerary into MongoDB
	result, err := collection.InsertOne(ctx, newItinerary)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": fmt.Sprintf("Error inserting itinerary: %s", err.Error())})
		return
	}

	// Extract the ID generated by MongoDB after insertion
	insertedID, ok := result.InsertedID.(primitive.ObjectID)
	if !ok {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Error extracting inserted ID"})
		return
	}

	newItinerary.Id = insertedID.String()

	// Respond with the created itinerary
	c.JSON(http.StatusCreated, newItinerary)
}
