package event

import (
	"context"
	"encoding/json"
	"fmt"
	"gopractice/models"
	"net/http"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

func (ec EventController) CreateEvent(w http.ResponseWriter, r *http.Request) {
	var newEvent models.Event
	err := json.NewDecoder(r.Body).Decode(&newEvent)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		fmt.Println("Error decoding request body:", err)
		return
	}

	collection := ec.client.Database("mongo-golang").Collection("events")
	ctx := context.TODO()

	result, err := collection.InsertOne(ctx, newEvent)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		fmt.Println("Error inserting event:", err)
		return
	}

	// Extract the ID generated by MongoDB after insertion
	insertedID, ok := result.InsertedID.(primitive.ObjectID)
	if !ok {
		w.WriteHeader(http.StatusInternalServerError)
		fmt.Println("Error extracting inserted ID")
		return
	}

	newEvent.Id = insertedID
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(newEvent); err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		fmt.Println("Error encoding JSON: ", err)
		return
	}
}
