package event

import (
	"context"
	"fmt"
	"net/http"

	"inititaryplanner/models"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func (ec EventController) CreateEvent(c *gin.Context) {
	var newEvent models.Event

	// Bind JSON request body to newEvent
	if err := c.ShouldBindJSON(&newEvent); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": fmt.Sprintf("Error decoding request body: %s", err.Error())})
		return
	}

	collection := ec.client.Database("mongo-golang").Collection("events")
	ctx := context.TODO()

	// Insert newEvent into MongoDB
	result, err := collection.InsertOne(ctx, newEvent)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": fmt.Sprintf("Error inserting event: %s", err.Error())})
		return
	}

	// Extract the ID generated by MongoDB after insertion
	insertedID, ok := result.InsertedID.(primitive.ObjectID)
	if !ok {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Error extracting inserted ID"})
		return
	}

	newEvent.Id = insertedID

	// Respond with the created event
	c.JSON(http.StatusCreated, newEvent)
}
