package user

import (
	"context"
	"encoding/json"
	"fmt"
	"gopractice/models"
	"net/http"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

func (uc UserController) CreateUser(w http.ResponseWriter, r *http.Request) {
	var newUser models.User
	err := json.NewDecoder(r.Body).Decode(&newUser)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		fmt.Println("Error decoding request body:", err)
		return
	}

	collection := uc.client.Database("mongo-golang").Collection("users")
	ctx := context.TODO()

	result, err := collection.InsertOne(ctx, newUser)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		fmt.Println("Error inserting user:", err)
		return
	}

	// Extract the ID generated by MongoDB after insertion
	insertedID, ok := result.InsertedID.(primitive.ObjectID)
	if !ok {
		w.WriteHeader(http.StatusInternalServerError)
		fmt.Println("Error extracting inserted ID")
		return
	}

	newUser.Id = insertedID
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(newUser); err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		fmt.Println("Error encoding JSON: ", err)
		return
	}
}
