// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"inititaryplanner/controllers"
	"inititaryplanner/dal"
	"inititaryplanner/dal/db"
	"inititaryplanner/service"
)

// Injectors from wire.go:

func InitializeMainController() (MainController, error) {
	mainMongoDB := db.GetMainMongoDatabase()
	attractionDal := dal.NewAttractionDal(mainMongoDB)
	attractionService := service.NewAttractionService(attractionDal)
	attractionController := controllers.NewAttractionController(attractionService)
	mainMainController := NewMainController(attractionController)
	return mainMainController, nil
}
